// packages/react/src/components/B10cksFallback.tsx
import type { IBContentBlock } from '@b10cks/client'
import type { ReactNode } from 'react'

type BlockWithType = IBContentBlock<string> & Record<string, unknown>

export interface B10cksFallbackProps {
  block: BlockWithType
  message?: ReactNode
}

export function B10cksFallback({ block, message }: B10cksFallbackProps) {
  return <div>{message ?? `Component for block type "${block.block || 'unknown'}" not found.`}</div>
}

// packages/vue/src/components/B10cksFallback.vue
<script setup lang="ts">
import type { IBContent } from '@b10cks/client'

export interface IB10cksFallbackProps {
  block: IBContent<string> & Record<string, never>
}

defineProps<IB10cksFallbackProps>()
</script>

<template>
  <div>Component for block type "{{ block.block }}" not found.</div>
</template>
